# Site settings
title:          Materials Engineering 
description:    "Learn Metallurgy"
baseurl:        "/tail"
url:

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Kolkata

# Google Analytics
google_analytics:

# Author
author:
  name:         Samarjeet Kumar Singh
  url:          https://samarjeet.xyz
  email:        samarjeet.xyz@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     /assets/css/_sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude:
  - README.md
  - LICENSE.md

# Disqus (Set to your disqus id)
disqus:
